#ifndef HYBRID_PLANNER__RRT_PRM_ASTAR_HPP_
#define HYBRID_PLANNER__RRT_PRM_ASTAR_HPP_

#include <vector>
#include <memory>
#include <random>
#include <array>
#include <unordered_map>

namespace hybrid_planner
{

// Axis-aligned obstacle box: (x, y, width, height) -- same convention as the
// Python obstacle_list of (ox, oy, w, h) tuples.
struct Obstacle
{
  double x;
  double y;
  double w;
  double h;
};

struct Point2D
{
  double x;
  double y;
};

// Equivalent of the Python "Node" class. Uses raw indices into a owning
// vector (NodeGraph::nodes) instead of Python object references, since that
// is the natural and safe way to express "graph node with neighbor list" in
// C++ without manual memory management headaches.
struct PlannerNode
{
  double x;
  double y;
  int parent = -1;                 // index into NodeGraph::nodes, -1 = none (root)
  std::vector<int> neighbors;       // indices into NodeGraph::nodes (PRM + RRT edges)
};

// Holds the full set of nodes generated by RRT + PRM densification, plus
// bookkeeping needed for A* over the resulting graph.
class NodeGraph
{
public:
  std::vector<PlannerNode> nodes;

  int addNode(double x, double y, int parent_idx);
};

// Result bundle returned by the planner so the ROS2 node can publish both
// the raw RRT path and the optimized A* path, plus visualization data.
struct PlanResult
{
  bool success = false;
  std::vector<Point2D> rrt_path;     // start -> goal, in order
  std::vector<Point2D> astar_path;   // start -> goal, in order (optimized)
  NodeGraph graph;                   // full graph for visualizing nodes/edges
  int random_node_count = 0;
};

class HybridRRTPRMAStar
{
public:
  HybridRRTPRMAStar(
    Point2D start,
    Point2D goal,
    std::vector<Obstacle> obstacles,
    double min_rand,
    double max_rand,
    double expand_dis = 0.5,
    int goal_sample_rate = 5,
    int max_iter = 3000,
    int k_neighbors = 10,
    unsigned int seed = 0,
    double safety_margin = 0.0);

  // Runs the full pipeline: RRT growth -> PRM densification (KD-tree style
  // k-NN, brute-force here since C++ has no scipy KDTree dependency by
  // default) -> A* over the resulting graph. Mirrors Python main().
  PlanResult plan();

private:
  // --- RRT phase (mirrors RRT.plan / steer / get_random_node / etc.) ---
  bool growRRT(NodeGraph & graph, int & goal_node_idx, std::vector<int> & rrt_path_indices);
  PlannerNode steer(const PlannerNode & from, const PlannerNode & to, double extend_length) const;
  Point2D sampleRandom();
  int nearestNodeIndex(const NodeGraph & graph, const Point2D & p) const;
  bool collisionFree(double x1, double y1, double x2, double y2) const;
  bool segmentIntersectsBox(double x1, double y1, double x2, double y2, const Obstacle & ob) const;
  double distToGoal(double x, double y) const;
  static double dist(double x1, double y1, double x2, double y2);

  // --- PRM densification phase (mirrors the KDTree k-NN block in main()) ---
  void densifyWithKNN(NodeGraph & graph);

  // --- A* phase (mirrors the heapq-based A* block in main()) ---
  bool runAStar(
    const NodeGraph & graph, int start_idx, int goal_idx,
    std::vector<int> & path_indices_out) const;

  Point2D start_;
  Point2D goal_;
  std::vector<Obstacle> obstacles_;
  double min_rand_;
  double max_rand_;
  double expand_dis_;
  int goal_sample_rate_;
  int max_iter_;
  int k_neighbors_;

  mutable std::mt19937 rng_;
  std::uniform_real_distribution<double> uniform_dist_;
  std::uniform_int_distribution<int> percent_dist_;

  int random_node_count_ = 0;
};

}  // namespace hybrid_planner

#endif  // HYBRID_PLANNER__RRT_PRM_ASTAR_HPP_
